# A,B=2,3
# Txt="@"
# print(A*B*Txt)


# A,B='3',3
# txt='@'
# print((A+txt)*B)
#concatnation - when two string are joined using +

# A,B,C=2,3,4
# print(A+B*C)

# operator precidence

#division of two
 #int will be float

# A,B=1,2
# print(A/B)

# A,B=2.5,2
# C=A//B #--> integer division gives int displayed as float
# print(C ,",", A/B) #= 1.0 1,25

# A,B=12,5
# print(A//B)  = 2

# A,B=-13.0,2
# print(A//B)  = -7.0

# A,B = -12,5
# print(A//B)

# round off to nearest integer less sthan or equal to the number



